version: '3'

services:

  cas:
    container_name: 'cas-cas'
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
    build:
      context: '.'
      dockerfile: 'Sito/Dockerfile'
    ports:
     - "80:80"
    restart: 'unless-stopped'
